let productos = [
  {
    stock: 5,
    id: 1,
    nombre: "malla1",
    tipo: "indumentaria",
    desc: "Para uso recreativo",
    precio: 1200,
    talle: "L",
    img: "./imagenes/malla1.jpg",
  },
  {
    stock: 4,
    id: 2,
    nombre: "malla2",
    tipo: "indumentaria",
    desc: "Para competencias",
    precio: 1100,
    talle: "L",
    img: "./imagenes/malla2.jpg",
  },
  {
    stock: 10,
    id: 3,
    nombre: "malla3",
    tipo: "indumentaria",
    desc: "Para competencias",
    precio: 1200,
    talle: "M",
    img: "./imagenes/malla3.jpg",
  },
  {
    stock: 13,
    id: 4,
    nombre: "malla4",
    tipo: "indumentaria",
    desc: "Short para todos los usos",
    precio: 1400,
    talle: "M",
    img: "./imagenes/malla4.jpg",
  },
  {
    stock: 15,
    id: 5,
    nombre: "malla5",
    tipo: "indumentaria",
    desc: "Para divertirte con amigos",
    precio: 1200,
    talle: "S",
    img: "./imagenes/malla5.jpg",
  },
  {
    stock: 4,
    id: 6,
    nombre: "antiparras1",
    tipo: "accesorios",
    desc: "Para divertirte en la pileta",
    precio: 1500,
    talle: "S",
    img: "./imagenes/antiparras1.jpg",
  },
  {
    stock: 6,
    id: 7,
    nombre: "antiparras2",
    tipo: "accesorios",
    desc: "Buceo",
    precio: 500,
    talle: "L",
    img: "./imagenes/antiparras2.jpg",
  },
  {
    stock: 9,
    id: 8,
    nombre: "antiparras3",
    tipo: "accesorios",
    desc: "Para la maxima competencia",
    precio: 500,
    talle: "L",
    img: "./imagenes/antiparras3.jpg",
  },
  {
    stock: 3,
    id: 9,
    nombre: "Colchoneta",
    tipo: "accesorios",
    desc: "Para Ejercitarte en casa",
    precio: 500,
    talle: "",
    img: "./imagenes/colchoneta1.jpg",
  },
  {
    stock: 11,
    id: 10,
    nombre: "Kettlebell",
    tipo: "accesorios",
    desc: "La pesa que sirve para tus entrenamientos en casa",
    precio: 700,
    talle: "",
    img: "./imagenes/kettlebells1.jpg",
  },
];
